# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0003_user_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('travel_date_from', models.CharField(max_length=255)),
                ('travel_date_to', models.CharField(max_length=255)),
                ('owners', models.ManyToManyField(related_name='trips', to='login_app.User')),
            ],
        ),
    ]
