# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_date_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_date_to',
            field=models.IntegerField(null=True),
        ),
    ]
