# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_auto_20171026_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_date_from',
            field=models.DateField(null=True),
        ),
    ]
