# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_user_date'),
        ('travel_app', '0005_auto_20171026_1518'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trip',
            managers=[
                ('travelManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='owners',
        ),
        migrations.AddField(
            model_name='trip',
            name='make_trip_id',
            field=models.ManyToManyField(related_name='maketrip', to='login_app.User'),
        ),
        migrations.AddField(
            model_name='trip',
            name='plan_trip_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plantrip', to='login_app.User'),
            preserve_default=False,
        ),
    ]
