# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20171023_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
